name: CI

on:
  push:
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
            - 'latest'
            - '5.24'
            - '5.22'
            - '5.20'
            - '5.18'
            - '5.16'
            - '5.14'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: >
          cpanm --quiet --notest --skip-satisfied Dist::Zilla &&
          dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied &&
          dzil listdeps | grep -vP '[^\w:]' | cpanm --verbose --notest

      - name: Build release
        run: dzil smoke --release --author
        
      # TODO: coverage

    


